### PR TITLE
Enumerate evse managers correctly in API module

### LINKED ISSUE #1710: Everest module API: evse_id is not initialized from the mapping
### Describe the bug

`API::init` enumerates evse managers based on the order these are listed in the connections: 

```
int evse_id = 1;
...
evse_id++
```

This is quite error prone, since the IDs should be assigned to the managers. We have a configuration with two managers; although the mappings were set up correctly (AC with id = 1, DC with id = 2), the links to the API modules were done in the opposite order, i.e. first we connected DC, then AC. Either we should mention this in the documentation (I could not find any reference) or the approach should be changed.

### EVerest Domain

Utility

### Affected EVerest Module

https://github.com/EVerest/everest-core/blob/main/modules/API/API/API.cpp

### To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by d-u-d-e**
## Describe your changes
Fix: `evse_id` should not be defined based on the order the evse managers are listed among the API connections.
Moved all the code requiring the `evse_id` parameter from the `init` function to the `ready` function where it's safe to call `call_get_evse` on the evse managers. 

Refactor: performed a couple of suggested changes from clang tidy

## Issue ticket number and link
Fix #1710 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

File: modules/API/API/API.cpp [hunk 1]
```diff
@@ -757,12 +687,73 @@ void API::ready() {
         this->charger_information = r_charger_information.at(0)->call_get_charger_information();
     }
 
+    // The following API commands require the EVSE managers to be initialized
```
Comment (Pietfried) [inline modules/API/API/API.cpp]:
```suggestion
    this->evse_manager_check.wait_ready();

    // The following API commands require the EVSE managers to be initialized
```

**Review by Pietfried — APPROVED** [review]
lgtm, please rebase and squash your commits into one
