### PR TITLE
EvseV2G: Adding a check for out of bounds parameters in charge parameter discovery

### LINKED ISSUE #1160: Handling out of bounds parameters
### Describe the bug

`EvseV2G` should set the `ResponseCode` for the `ChargeParameterDiscoveryRes` to `Failed` if a maximum parameter of the `ChargeParameterDiscoveryReq` message is below the minimum value of the Evse. E.g. `EVMaximVoltage` = 200V, `EvseMinimumVoltage` = 220V

This applies to current, voltage and power.

### EVerest Domain

ISO15118

### Affected EVerest Module

EvseV2G

### To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MarzellT**
## Describe your changes

This pull request adds a check for a potential charge parameter mismatch between the ev max values and the evse min values.

## Issue ticket number and link

Closes #1160

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

File: modules/EvseV2G/iso_server.cpp [hunk 1]
```diff
@@ -1304,6 +1304,16 @@ static enum v2g_event handle_iso_charge_parameter_discovery(struct v2g_connectio
             req->DC_EVChargeParameter.EVMaximumVoltageLimit.Value < 0) {
             res->ResponseCode = iso2_responseCodeType_FAILED_WrongChargeParameter; // [V2G2-477]
         }
+        if (req->DC_EVChargeParameter.EVMaximumCurrentLimit.Value *
```
[the remark this answers is not in the document]
Comment (MarzellT) [reply modules/EvseV2G/iso_server.cpp]: Yes that makes sense. I changed it

**Review by SebaLukas — APPROVED** [review]
:+1:

File: modules/EvseV2G/iso_server.cpp [hunk 2]
```diff
@@ -1322,6 +1322,21 @@ static enum v2g_event handle_iso_charge_parameter_discovery(struct v2g_connectio
             req->DC_EVChargeParameter.EVMaximumVoltageLimit.Value < 0) {
             res->ResponseCode = iso2_responseCodeType_FAILED_WrongChargeParameter; // [V2G2-477]
         }
+
+        constexpr auto physical_value_to_float = [](const iso2_PhysicalValueType& pv) {
```
Comment (SebaLukas) [inline modules/EvseV2G/iso_server.cpp:1326]: Good catch. Have look into the EvseV2G if there is any similiar function

Comment (barsnick) [reply modules/EvseV2G/iso_server.cpp:1326]: `calc_physical_value()`:
https://github.com/EVerest/everest-core/blob/2025.5.0/modules/EvseV2G/tools.cpp#L178-L180

libiso15118 has this (but should perhaps also use double):
https://github.com/EVerest/libiso15118/blob/v0.6.0/src/iso15118/message/common_types.cpp#L153-L155

Comment (MarzellT) [reply modules/EvseV2G/iso_server.cpp:1326]: I looked but I coudln't find a similar function

Comment (MarzellT) [reply modules/EvseV2G/iso_server.cpp:1326]: > `calc_physical_value()`: https://github.com/EVerest/everest-core/blob/2025.5.0/modules/EvseV2G/tools.cpp#L178-L180
> 
> libiso15118 has this (but should perhaps also use double): https://github.com/EVerest/libiso15118/blob/v0.6.0/src/iso15118/message/common_types.cpp#L153-L155

Thanks for pointing that out. I didn't see it. I will use that function instead
