### PR TITLE
fix: adding missing OCPP1.6 Configuration Keys (#1796)

### LINKED ISSUE #1796: Hidden OCPP1.6 Configuration Keys
### Describe the bug

The following configuration keys in OCPP1.6 can be configured but can not be retrieved by the CSMS:
- EnableTLSKeylog
- LogRotation
- LogRotationDateSuffix
- LogRotationMaximumFileCount
- LogRotationMaximumFileSize
- TLSKeylogFile
- UseTPM
- UseTPMSeccLeafCertificate

The reason for this is that they are missing cases in the `get` function of ChargePointConfiguration.
`std::optional<KeyValue> ChargePointConfiguration::get(const CiString<50>& key)`

To solve this issue they can simply be added to this function.

### EVerest Domain

OCPP, OCPP1.6

### Affected EVerest Module

OCPP

### To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ThatsLucas**
OCPP 1.6: add missing configuration keys to ChargePointConfiguration::get()

Fixes #1796.

Expose configuration keys that were configurable locally but not retrievable via OCPP 1.6 GetConfiguration due to missing cases in ChargePointConfiguration::get().

## Issue ticket number and link
https://github.com/EVerest/everest-core/issues/1796

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Comment by Pietfried** [comment]
Hi @ThatsLucas , thanks for the contribution! The changes look good. Unfortunately https://github.com/EVerest/everest-core/commit/0a2c98dc808e34d4ea3852ca397d42a8c2f49458 introduced conflicts. Can you rebase and resolve it? Please make sure you squash your commits into one.

**Comment by Pietfried** [comment]
> Im not sure whats wrong with the unit tests

You can download the ctest-report artifact from https://github.com/EVerest/everest-core/actions/runs/21981574665?pr=1801 or alternatively run the unit tests locally. Feel free to let us know if you need help with analyzing the issue.

File: lib/everest/ocpp/include/ocpp/v16/charge_point_configuration_devicemodel.hpp
Comment (james-ctc) [inline lib/everest/ocpp/include/ocpp/v16/charge_point_configuration_devicemodel.hpp:1]: The existing file has methods listed in alphabetical order - these updates should follow the existing standard used in the file.

File: lib/everest/ocpp/include/ocpp/v16/charge_point_configuration_interface.hpp
Comment (james-ctc) [inline lib/everest/ocpp/include/ocpp/v16/charge_point_configuration_interface.hpp:1]: The existing file has methods listed in alphabetical order - these updates should follow the existing standard used in the file.

File: lib/everest/ocpp/lib/ocpp/v16/charge_point_configuration_devicemodel.cpp
Comment (james-ctc) [inline lib/everest/ocpp/lib/ocpp/v16/charge_point_configuration_devicemodel.cpp:1]: The existing file has methods listed in alphabetical order - these updates should follow the existing standard used in the file and the order in the header file

File: lib/everest/ocpp/lib/ocpp/v16/known_keys.cpp [hunk 1]
```diff
@@ -26,10 +26,6 @@ using ocpp::v16::keys::valid_keys;
     key(LogMessages) \
     key(LogMessagesRaw) \
     key(LogMessagesFormat) \
-    key(LogRotation) \
-    key(LogRotationDateSuffix) \
-    key(LogRotationMaximumFileSize) \
-    key(LogRotationMaximumFileCount) \
```
Comment (james-ctc) [inline lib/everest/ocpp/lib/ocpp/v16/known_keys.cpp:32]: It isn't obvious why are these no longer considered read-only.
They are still read only in charge_point_configuration.cpp (line 659)
And both implementations should be consistent.
```
KeyValue ChargePointConfiguration::getLogRotationKeyValue() {
    KeyValue kv;
    kv.key = "LogRotation";
    kv.readonly = true;
    kv.value.emplace(ocpp::conversions::bool_to_string(this->getLogRotation()));
    return kv;
}
```

File: lib/everest/ocpp/tests/lib/ocpp/v16/v2config/test_custom.cpp [hunk 2]
```diff
@@ -177,10 +186,13 @@ TEST_P(Configuration, Set) {
...
     EXPECT_FALSE(kv.value().readonly);
 
-    // hidden key - these are read-only
+    // read-only key
 
     // check key exists and has a value
     EXPECT_EQ(get()->getTLSKeylogFile(), "/tmp/ocpp_tls_keylog.txt");
+    kv = get()->get("TLSKeylogFile");
+    ASSERT_TRUE(kv);
+    EXPECT_TRUE(kv.value().readonly);
```
Comment (james-ctc) [inline lib/everest/ocpp/tests/lib/ocpp/v16/v2config/test_custom.cpp:195]: minor - in the other checks, read only is done after checking the value.
for consistency the checks should be done in the same order

File: lib/everest/ocpp/tests/lib/ocpp/v16/v2config/test_custom.cpp [hunk 3]
```diff
@@ -297,10 +309,13 @@ TEST_F(Configuration, SetV2) {
     EXPECT_EQ(kv.value().value, "1201");
     EXPECT_FALSE(kv.value().readonly);
 
-    // hidden key - these are read-only
+    // read-only key
```
Comment (james-ctc) [inline lib/everest/ocpp/tests/lib/ocpp/v16/v2config/test_custom.cpp]: this section of the test is no longer needed since there are no hidden keys other than AuthorizationKey which is tested in test_security.cpp

File: lib/everest/ocpp/lib/ocpp/v16/known_keys.cpp (hunk 1 above)
Comment (ThatsLucas) [reply lib/everest/ocpp/lib/ocpp/v16/known_keys.cpp:32]: They are still in read only i just mooved them at the bottom of the list when i checked if none was missing. I will moove them back.
I doubled checked Implementations are consistent.

File: lib/everest/ocpp/include/ocpp/v16/charge_point_configuration_devicemodel.hpp
Comment (ThatsLucas) [reply lib/everest/ocpp/include/ocpp/v16/charge_point_configuration_devicemodel.hpp:1]: Ok ! Will change this

File: lib/everest/ocpp/include/ocpp/v16/charge_point_configuration_interface.hpp
Comment (ThatsLucas) [reply lib/everest/ocpp/include/ocpp/v16/charge_point_configuration_interface.hpp:1]: done

File: lib/everest/ocpp/lib/ocpp/v16/charge_point_configuration_devicemodel.cpp
Comment (ThatsLucas) [reply lib/everest/ocpp/lib/ocpp/v16/charge_point_configuration_devicemodel.cpp:1]: done

File: lib/everest/ocpp/tests/lib/ocpp/v16/v2config/test_custom.cpp (hunk 2 above)
Comment (ThatsLucas) [reply lib/everest/ocpp/tests/lib/ocpp/v16/v2config/test_custom.cpp:195]: Should be good now

File: lib/everest/ocpp/tests/lib/ocpp/v16/v2config/test_custom.cpp (hunk 3 above)
Comment (ThatsLucas) [reply lib/everest/ocpp/tests/lib/ocpp/v16/v2config/test_custom.cpp]: i removed it

**Review by Pietfried — APPROVED** [review]
